### ISSUE TITLE
LAcheck: Duplicate overlap

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/FALCON-integrate#103] opened 2016-11-11 23:31 UTC
Hello,
I'm getting an error with falcon-integrate/1.7.4 and 1.7.7 versions that I do not get with version 0.7.3.  In the 0-rawreads stage, it looks like it's a 256 error where a heartbeat file goes missing before it can remove it, causing the critical error.  I've run 30 datasets through as a test and it happens for nearly half of them, whereas the same 30 datasets run fine using version 0.7.3.  I'm not sure how to resolve this:

all.log:
2016-10-26 23:20:27,363 - pypeflow.controller - DEBUG - #jobsReadyToBeSubmitted: 0
2016-10-26 23:20:27,363 - pwatcher.fs_based - DEBUG - query(which='list', jobids=<6>)
2016-10-26 23:20:27,368 - pwatcher.fs_based - DEBUG - Status RUNNING for heartbeat:heartbeat-Jbeb0dbf2ca18dd31dd5f8a2339c16df565d787c936d32df98cc2072a078fb018
2016-10-26 23:20:27,368 - pwatcher.fs_based - DEBUG - Status RUNNING for heartbeat:heartbeat-Jd847ff3314ee40e38bd534369af0a0c237067dff683caba3b3d3f24a9fb4ba57
2016-10-26 23:20:27,368 - pwatcher.fs_based - DEBUG - Status RUNNING for heartbeat:heartbeat-J7e95a4b4312d74183781cbdfd6bfd99c4bc07b3f643a10bdd5172cb1703fa9b7
2016-10-26 23:20:27,368 - pwatcher.fs_based - DEBUG - Status RUNNING for heartbeat:heartbeat-Jc5c7aef346214605b29b63a643655894f22b4cbffaf3bb6abf166cf7e0ee4fce
2016-10-26 23:20:27,369 - pwatcher.fs_based - DEBUG - Unable to remove heartbeat
 '/fungal_std/rqc_tests/1_1_0/falcon_1_7_7/AUTPG_s8362/falcon/mypwatcher/heartbeats/heartbeat-J0bc399237c78ad0c02298b4bb884f72b9
fb752cc07cc8c72c1740e3e127ef0c0' when sentinal was found in exit-sentinels listdir.
Traceback (most recent call last):
  File "/usr/common/jgi/assemblers/falcon/1.7.7/FALCON-integrate/fc_env/lib/python2.7/site-packages/pwatcher/fs_based.py", line 553, in get_status
    os.remove(heartbeat_path)
OSError: [Errno 2] No such file or directory: '/fungal_std/rqc_tests/1_1_0/falcon_1_7_7/AUTPG_s8362/falcon/mypwatcher/heartbeats
/heartbeat-J0bc399237c78ad0c02298b4bb884f72b9fb752cc07cc8c72c1740e3e127ef0c0'
2016-10-26 23:20:27,373 - pwatcher.fs_based - DEBUG - Status EXIT 256 for heartbeat:heartbeat-J0bc399237c78ad0c02298b4bb884f72b9fb752cc07cc8c72c1740e3e127ef0c0
2016-10-26 23:20:27,373 - pwatcher.fs_based - DEBUG - Status RUNNING for heartbeat:heartbeat-Ja1bdf7841796c08e9dcc12d787d9908f4c7ef6eff076bc7a8657df68fef4476b
2016-10-26 23:20:27,373 - pypeflow.pwatcher_bridge - ERROR - Task Fred{'URL': 'task://localhost/d_000b_raw_reads'} failed with exit-code=256
2016-10-26 23:20:27,379 - pypeflow.controller - DEBUG - Total # of running threads: 1; alive tasks: 6; sleep=1.000000, loopN=1506
2016-10-26 23:20:28,384 - pypeflow.controller - DEBUG - message for task://localhost/d_000b_raw_reads: 'fail'
2016-10-26 23:20:28,384 - pypeflow.controller - INFO - Failure ('fail'). Joining 'task://localhost/d_000b_raw_reads'...

falcon.log:
[ERROR]Task Fred{'URL': 'task://localhost/d_000b_raw_reads'} failed with exit-code=256

**Comment by pb-cdunn** [comment] 2016-11-12 16:36
That error is trapped. (It helps us learn about your filesystems latency.) It is not the real error.

Look in the run directory for the failed job. Look for `pwatcher.dir/stderr`.

**Comment by jasmynp** [comment] 2016-11-13 23:39
Hmm...I had looked at the pwatcher.dir/stderr of the 256 error and I couldn't find any obvious reason for the error code other than something than this duplicate overlap:
raw_reads.7.raw_reads.7.C3: Duplicate overlap (518322 vs 505607)
So when I saw the failure message posted above, I assumed that was the issue.  Can you take a peek at the attached is the stderr of the job that failed? Thanks.
[stderr.txt](https://github.com/PacificBiosciences/FALCON-integrate/files/588176/stderr.txt)

**Comment by pb-cdunn** [comment] 2016-11-15 17:20
What is your version (commit) of the DALIGNER submodule? In theory, this problem has been fixed.

**Comment by jasmynp** [comment] 2016-11-15 17:48
I'm waiting to hear back from our nersc consultant who handles the installations of the modules.  It looks like the package was installed all together, but I couldn't tell exactly what version/commit was being loaded. There is no command-line option of DALIGNER to check?

**Comment by pb-cdunn** [comment] 2016-11-15 18:07
Versioning each component is time-consuming and error-prone, and it may imply that the components guarantee backwards-compatibility independently. It's easier to keep track of git-commits at installation time.

But you don't really need a sysadmin for this. Just try a "user-install" for yourself. Just follow the wiki. It takes about a minute. Then just use the environment variables from `env.sh`.

**Comment by jasmynp** [comment] 2016-11-15 19:19
Hi Chris, I'm not exactly following your last reply, but we have our sysadmin install the falcon modules because we run them on a large system in a productionized setting where others use it as well within JGI.  So he tends to just do a git checkout of the latest version and sets up a module for us, so it's not my own instance.  Here is what our admin said about the checkout of this version of falcon's install:

" The build script we use just used git to checkout 1.7.7, and then runs the "travis.sh" script to make, and then copies pypeFLOW and pwatcher into its python site-packages. So, I would assume the version of DALIGNER was whatever was pulled in from the git repo at the time I did the 1.7.7 checkout. "

We took a peek at the env.sh and everything is pointing to where 1.7.7 was installed from the checkout. I'm going to have him do a rebuild from the git clone of 1.7.7 and see if anything changes.  I will also request the checkout of the latest release 1.8.2 and see if we are still getting issues.  I will check in again in a bit, unless you have any other clues.

**Comment by pb-cdunn** [comment] 2016-11-15 20:09
>  into its python site-packages

This can be problematic. The modules are not released independently, like PyPI. It is important for your sysadmin to guarantee that they are over-writing any previous installation. 

> the latest release 1.8.2 and see if we are still getting issues

Good. We do not have personnel to support multiple older versions. But on the latest version, we are eager to help because you users also helping us to validate on various systems where it may be difficult for us to test.

However, the most important thing is to absolutely certain of the DALIGNER version. If LAcheck is failing, you either have an old version of DALIGNER, or we need to submit your test-case to gene myers. (Gene does not add version numbers either.)

**Comment by jasmynp** [comment] 2016-11-16 01:06
Ok, so I ran same dataset with updated 1.7.7.  Still same issue. 
Ran it with latest 1.8.2 code.  Same issue failure again but a little bit more verbose stderr.   Interestingly, if I manually run rj_000b.sh, it doesn't spit out any stderr messages after this line: "raw_reads.7.raw_reads.7.N3: 101,192 all OK", 

Instead, it just dies, whereas I find more messages under the stderr file under mypwatcher/jobs/ so I couldn't tell what script writes the stderr. I thought it all happened with rj_000b.sh.

Attached is the stderr of the failed job as well as the log file from the 1.8.2 install. Let me know if you need the job/stdout. If you want me to file a ticket with the customer portal, I can do that too.  Note, this error happens for roughly 15 datasets out of 30.  The other 15 ran successfully.  These are fungal data sets.

below is part of the stderr:

```
  raw_reads.7.raw_reads.7.C3: Duplicate overlap (518322 vs 505607)
  raw_reads.7.raw_reads.7.N0: 94,937 all OK
  raw_reads.7.raw_reads.7.N1: 99,412 all OK
  raw_reads.7.raw_reads.7.N2: 101,445 all OK
  raw_reads.7.raw_reads.7.N3: 101,192 all OK
2016-11-15 14:54:53,846 - root - CRITICAL - Error in /global/common/genepool/jgi/assemblers/falcon/1.8.2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '//1_1_0/falcon_1_8_2/AUTPG_s8362/falcon/0-rawreads/job_000b/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/common/usg/languages/python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/common/usg/languages/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/global/common/genepool/jgi/assemblers/falcon/1.8.2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow/do_task.py", line 149, in <module>
    main()
  File "/global/common/genepool/jgi/assemblers/falcon/1.8.2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow/do_task.py", line 141, in main
    run(**vars(parsed_args))
  File "/global/common/genepool/jgi/assemblers/falcon/1.8.2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow/do_task.py", line 129, in run
    do_support.run_bash(script_fn)
  File "/usr/common/jgi/assemblers/falcon/1.8.2/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /global/projectb/scratch/jasmynp/fungal_std/rqc_tests/1_1_0/falcon_1_8_2/AUTPG_s8362/falcon/0-rawreads/job_000b/rj_000b.sh'

real    10m4.849s
user    36m12.080s
sys     1m39.195s
 returned: 256
```

[stderr.txt](https://github.com/PacificBiosciences/FALCON-integrate/files/593495/stderr.txt)
[falcon182.log.txt](https://github.com/PacificBiosciences/FALCON-integrate/files/593496/falcon182.log.txt)

**Comment by pb-cdunn** [comment] 2016-11-16 16:21
> raw_reads.7.raw_reads.7.C3: Duplicate overlap (518322 vs 505607)

I submitted this bug to Gene Myers many months ago. This is supposed to be solved. Are you _definitely_ using the latest PacBio/DALIGNER?

I suggest that you build our DALIGNER yourself and run the bash script for a single job in a shell where you can monitor it. Nobody is seeing this anymore in our internal testing.

**Comment by jasmynp** [comment] 2016-11-17 18:59
Hi.  Yes, I'm sure it is the latest pacBio/daligner.  To do one more test, I did this:
git clone https://github.com/PacificBiosciences/FALCON-integrate.git  (to pull 1.8.2)
I built it and ran source env.sh and verified that the daligner was pointing to the directory where I ran git clone.  I ran rj_00b.sh manually under job_000b/ and it still complained of duplicate overlap.

I also took the daligner from thegenemeyers repo and tested that daligner and got the same issue.  
git clone https://github.com/thegenemyers/DALIGNER.git
But doing a diff of the daligner.c from thegenemeyers repo and the daligner.c available in the 1.8.2 are different.  Aren't they supposed to be the same?

[daligner.genemeyers.vs.1.8.2.diff.txt](https://github.com/PacificBiosciences/FALCON-integrate/files/598195/daligner.genemeyers.vs.1.8.2.diff.txt)

I've also had two other users run falcon/1.8.2 on the same dataset to make sure I didn't have any environment issues.

Perhaps I should forward along my data set and see if you get the same issue.

**Comment by pb-cdunn** [comment] 2016-11-18 00:04
> Aren't they (daligner souces) supposed to be the same?

We have slight changes for Falcon-consensus. We are very careful to stay up-to-date though. Thank you for testing with the latest from thegenemyers too. That is useful info.

> Perhaps I should forward along my data set and see if you get the same issue.

Yes, if possible, that would be very helpful.

**Comment by jasmynp** [comment] 2016-11-18 00:24
Thanks for all your help with this.  We try to push our pipelines to stay up to date with the versions.  

So we already have an ftp setup for a mock community project.  Let me know if I should use the same link or if we should talk offline etc.

**Comment by pb-cdunn** [comment] 2016-11-18 00:49
Here is fine. It's a good way to track things. But you can send me ftp password or link privately if necessary.

**Comment by sjin09** [comment] 2016-12-19 05:40
Dear @pb-cdunn 

I would like to mention that I am also experiencing exactly the same problem with the FALCON de novo assembly of a human genome. I look forward to the the issue being resolved soon!

**Comment by pb-jchin** [comment] 2016-12-19 05:46
@sjin09 the fastest way you can do is find the line of the code calling LAcheck and disable checking.  If you file system is good, your files may not need to be checked. The LAcheck is just for double checking in the case that if the file system is too slow, some corrupted files may exist. Unfortunately, LAcheck itself also brings some problem unexpectedly.

This is why this code is open source.  It gives you the opportunity to fix special issue on your side by yourself. We already know the problem and development and test will need time for robustness especially for cutting edge stuff. Thanks for your understanding.

**Comment by sjin09** [comment] 2016-12-19 06:00
Dear @pb-jchin 

I will try that immediately. Thank you for the suggestions. I am really looking forward to the new de novo assembly results.

Best,
Jin

**Comment by pb-cdunn** [comment] 2016-12-19 16:20
When the error is caused by file-system latency, the best solution today is to run outside NFS, e.g. /tmp. We run with the setting

    use_tmpdir = /scratch

That way, the merge task will always see an up-to-date version of all .las files. That seems to solve the problem for us. In fact, the latest daligner from Gene Myers actually runs in /tmp always. I don't think he realized that he was solving this problem, but he was.

**Closed as completed by pb-cdunn** 2016-12-19 16:20 UTC

**Comment by pb-cdunn** [comment] 2017-01-13 23:06
Internally: SE-182

https://jira.pacificbiosciences.com/browse/SE-182

**Comment by aechchiki** [comment] 2018-07-30 15:07
@pb-cdunn any idea on how to disable LAcheck included in latest non-beta version of falcon (https://pb-falcon.readthedocs.io/en/latest/_downloads/install_unzip_180312.sh)?

from J. Chin's suggestions: https://twitter.com/aechchiki/status/1023850543083606021
to help me fix the issue: https://github.com/PacificBiosciences/FALCON/issues/660

thanks in advance

**Comment by pb-cdunn** [comment] 2018-07-31 15:02
Latest "non beta"? They're all "beta" right now, I think. I'll comment there.
